### ISSUE TITLE
What's the rollbar server key

### ISSUE THREAD

**Issue by pmatos** [psykzz/flask-rollbar#21]
From the example, it's not clear what the rollbar server key is:
```
'ROLLBAR_SERVER_KEY': os.environ.get('ROLLBAR_SERVER_KEY'),
```

According to rollbar docs there are several keys per project: https://rollbar.com/docs/api/
```
post_server_item
    Can perform all POST requests
post_client_item
    Can perform POST requests to /deploy/ and /item/, but only if the item has a client-side platform.
read
    Can perform all GET requests
write
    Can perform PATCH requests to change item statuses. 
```

**Comment by psykzz** [comment]
`POST_SERVER_ITEM_ACCESS_TOKEN` is the one.
This changed since when i first created this. An alternative - https://github.com/rollbar/pyrollbar is also available from Rollbar officially now.
